### ISSUE TITLE
error when cargo build

### ISSUE THREAD

**Issue by adals** [tomaka/rouille#131]
Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to select a version for `phf` (required by `postgres`):
all possible versions conflict with previously selected versions of `phf`
  version 0.7.16 in use by phf v0.7.16
  possible versions to select: 0.7.19

$ rustc -Vv
rustc 1.14.0 (e8a012324 2016-12-16)
binary: rustc
commit-hash: e8a0123241f0d397d39cd18fcc4e5e7edde22730
commit-date: 2016-12-16
host: x86_64-apple-darwin
release: 1.14.0
LLVM version: 3.9

**Comment by tomaka** [comment]
That's probably not an error with rouille but with postgres.

Try running `cargo update`. If it still doesn't work, open an issue for postgres with the content of your `Cargo.toml`.

**Comment by adals** [comment]
thanks cargo update 
solved my problem
