### ISSUE TITLE
How to stop the server?

### ISSUE THREAD

**Issue by leovailati** [tomaka/rouille#139]
Hello,

What is the appropriate way to stop the server?

According to documentation for `Server::run()`:

> Runs the server **forever**, or until the listening socket is somehow force-closed by the operating system.

And `start_server` never returns (`!`).

**Comment by tomaka** [comment]
`server.run()` is equivalent to `loop { server.poll() }`, so if you want to stop the server you can just call `server.poll()` repeatedly until some condition becomes true.

**Comment by leovailati** [comment]
Thank you for your answer. Quick follow-up question: is there a way to exit the handler without responding to a request?

**Comment by tomaka** [comment]
Unfortunately that's not possible.

**Comment by leovailati** [comment]
I see, thank you very much!
