### ISSUE TITLE
Use serde instead of rustc_serialize?

### ISSUE THREAD

**Issue by icefoxen** [tomaka/rouille#149]
Or maybe have it available a feature flag.

In theory, it doesn't REALLY matter, but in practice, I use `reqwest` for unit tests, which serializes things to JSON using serde.  So far the serde and rustc_serialize representations have always matched, but there's no guarantee that will always be the case.

I will try to work on a PR for this if you want.

**Comment by cardoe** [comment]
I think I have this implemented in https://github.com/cardoe/rouille/tree/serde but can't get the docs to be happy with it.
