### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mentalbrew** [tomaka/rouille#165]
Would there be any problem with releasing a version with serde support now that it has been merged? Is there anything else holding it up?

**Comment by tomaka** [comment]
The only thing holding things up is that we may want to put as many breaking changes as possible into the same version.
So let's merge #164, and then we'll release version 2.0.

**Comment by mentalbrew** [comment]
Thanks Pierre! Much appreciated.

**Comment by coder543** [comment]
The timing of all of this is great. I was just about to post a similar issue. I'm looking at web frameworks, and Rouille seems to be the most highly recommended, and Serde support would be nice to have.

**Comment by coder543** [comment]
It looks like #164 got merged a few days ago. what's the status on this? I do see that issue #167 has been opened.

**Comment by tomaka** [comment]
If you open a PR that modifies the version of the library I will merge it and it will automatically publish it!

**Comment by coder543** [comment]
alright, I have opened the PR!

**Comment by MightyPork** [comment]
Just came here to open the same issue for >3.0.0

I need `server.poll_timeout()`, now I'm pulling it from git but an official version on crates.io would be nicer…
