### ISSUE TITLE
be able to end rouille

### ISSUE THREAD

**Issue by mwarning** [tomaka/rouille#190]
There should be a way to end rouille. The passed closure just does blocking IO and there seems to be no way to end the thread from another thread..

**Comment by brycefisher** [comment]
Digging through issues found this:
https://github.com/tomaka/rouille/issues/139#issuecomment-297480690

Basically, just call `server.poll()` until you want to stop the server.

**Comment by mwarning** [comment]
yes, but only until there is an incoming request..
Maybe you can do a dummy connection..

**Comment by mwarning** [comment]
ok, I will create a dummy connection to trigger the exit. Not the nicest solution. But it will probably work.
