### ISSUE TITLE
Rust 2018 macro compatibility

### ISSUE THREAD

**Issue by dkaste** [tomaka/rouille#222]
In Rust 2018 it is generally preferred to write `use` statements to import macros. Due to the implementation details of the macros in `rouille` (using crate-local macros within macros), it is currently impossible to import them that way.

There are two ways to fix this:
* ~~To stay compatible with Rust versions below 1.30: [`local_inner_macros`](https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#macros-using-local_inner_macros)~~
* To be future-proof: [`$crate::`](https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#macros-with-crate-prefix)

I'm unsure which option would be more suitable for `rouille`, but I am willing to implement either of these changes.

Edit: Just realized that the minimum Rust version for this project is already above 1.30.

**Comment by bradfier** [comment]
Resolved by merging #223
