### ISSUE TITLE
Could be used whole path as one String in router?

### ISSUE THREAD

**Issue by jeyraof** [tomaka/rouille#232]
```rust
router!(request,
    // block 1
    (GET) (/) => { ... },

    // block 2: here
    (GET) (/{slug: String}) => { ... },
)
```

It pretty matched when paths are:

- `/` => block1
- `/asdf` => block2.

But I want to match `/nested/path` to block 2, and slug needed to be evaluated as `nested/path`.

Can i do this one?

**Comment by bradfier** [comment]
I agree with @marinintim here, your best bet is to use a catch-all arm and then match on `.url()` or `.raw_url()`, this will give you a bit more control in case you also want (or don't want) to capture query parameters.

That's partly why there's no trivial way to implement what you ask for in `router!`, matching 'the whole path' isn't a well defined statement and different use-cases will treat it differently.
