### ISSUE TITLE
Maintenance Status

### ISSUE THREAD

**Issue by bradfier** [tomaka/rouille#235]
Hi

First off, thank you for creating Rouille, it's a wonderful library in a world of overcomplicated async frameworks.

Correlated to https://github.com/tiny-http/tiny-http/issues/199, I wondered if there were any plans to continue maintaining this crate? I've noticed some bugfix and compatible enhancement PRs have been open for over two years without further comment.

If you feel it's feature complete that's totally understandable, but if you would like some help responding to issues and PRs, or if you simply don't have time to remain involved with the project, then I'm ready to help.

**Comment by tomaka** [comment]
Hi,

Indeed, the crate is mostly feature complete and I really don't have the bandwidth (nor motivation) to maintain it.

**Comment by bradfier** [comment]
While I'm sorry to hear that, it's completely understandable.

Would you be open to adding a co-maintainer? We've been running a forked version in production for some time now and there are a couple of improvements that would benefit other users without expanding the API surface too much:

- #219 For those building apps that need to be able to gracefully stop the threadpool.
- #223 For people trying to use the `router!` macro in 2018 style contexts.

In addition, it would be nice to try and bring Rouille up to the latest version of `tiny-http` so downstream users can get the benefit of the security fixes since 0.6.

All of the above _should_ be possible without making breaking API changes.

**Comment by tomaka** [comment]
(sorry for the late answer, you were on page 2 of my notifications)

I've added you as collaborator!

**Comment by bradfier** [comment]
Oh great, thanks! I'll accept once I get to a computer.

I think it will be worth moving away from Travis in the short term, they are effectively removing the the free build time available to open source as part of being acquired.

If you're amenable happy with GitHub, I added a GHA workflow to `tiny-http` which I can copy over here trivially, we can tie Crates.io releases to GitHub releases using the `on: [release]` directive.

**Comment by bradfier** [comment]
I've opened the PR in question over at #236 :slightly_smiling_face:
