### ISSUE TITLE
Clippy suggests replacing str::{starts,ends}_with with strip_{prefix,suffix}

### ISSUE THREAD

**Issue by rogertsui0923** [tomaka/rouille#237]
First of all, many thanks for the Rouille library.
Running Clippy 0.1.51 emits this [warning](https://rust-lang.github.io/rust-clippy/master/index.html#manual_strip). I assume it is due to [this pattern](https://github.com/tomaka/rouille/blob/master/src/router.rs#L315-L317) in the `router!` implementation.

**Comment by bradfier** [comment]
You're right! Unfortunately that feature isn't stable on 1.41.1 (our MSRV) so we can't just swap out the calls.

I thought I had added `#[allow]` for the lints we "can't" fix but I must have missed this one.

**Comment by rogertsui0923** [comment]
Thanks for the quick reply! That makes sense.

**Comment by bradfier** [comment]
I was able to silence the error by setting an `msrv` value in `clippy.toml` :slightly_smiling_face: 

That change is in c86bbf422d1d6 and will be in a release at some point this week.
