### ISSUE TITLE
`router!()` triggers `manual_strip` clippy warning

### ISSUE THREAD

**Issue by ravenexp** [tomaka/rouille#244]
Since MSRV was bumped to 1.48, `.strip_prefix()` method became available.

https://rust-lang.github.io/rust-clippy/master/index.html#manual_strip

Example instance:
https://github.com/tomaka/rouille/blob/b49b26c280a11e4e32884b300128e87865dff380/src/router.rs#L315

**Comment by bradfier** [comment]
Fixed and released as [v3.3.1](https://github.com/tomaka/rouille/releases/tag/v3.3.1), thanks for the report!
