### ISSUE TITLE
can rouille be used to return a binary?

### ISSUE THREAD

**Issue by jhjacobs81** [tomaka/rouille#250]
as per: https://users.rust-lang.org/t/i-need-a-bit-of-guidance/71830

i am looking for a simple framework that can take a token, input this into an XML file, then run a batch file (which compiles the files into an MSI) and return the MSI for download by the user?

**Comment by bradfier** [comment]
Hi @jhjacobs81, yes that's an entirely sensible use case for Rouille.

Take a quick look at the [Hello World](https://github.com/tomaka/rouille/blob/master/examples/hello-world.rs) example, you'll want to return the data that comprises your MSI with [`rouille::Response::from_data`](https://docs.rs/rouille/3.5.0/rouille/struct.Response.html#method.from_data), probably with the MIME type set to `application/x-msi`, but `application/octet-stream` would likely work just as well, depending on browser.

**Comment by bradfier** [comment]
Yes, I think almost exactly :slightly_smiling_face: 

Will your compile stage (step 3) take a particularly long time? Be aware that this will block one of Rouille's threads, so you'll only be able to serve as many concurrent requests as you have threads in your thread pool.

**Comment by jhjacobs81** [comment]
My apologies for not responding sooner, ive been very busy elsewhere.

compilation will be a batch script that produces an MSI. I have not figured that part out yet because i’m a Rust beginner :) but i suspect we will only call this route once a day, so that shouldnt be a problem :) 

i’m still figuring out how to create a basic CRUD webapp with it :)
