### ISSUE TITLE
How to obtain server's IP address from within request handler?

### ISSUE THREAD

**Issue by wpd** [tomaka/rouille#251]
Following the websocket.rs example, how can I determine the server's IP address for use by the javascript code?

In your example, you start the server on `localhost:8000`, and therefor know you can reach back to the server from the javascript code at that address.  But how would one find the address of a server started on `Ipv4Addr::UNSPECIFIED`?

I see that I can manually create the server with `Server::new()`, and that I can obtain the server's address with `server.server_addr()`, but, by the time I can obtain that, I have already passed/moved everything into the closure for the response handler.

Should I just stuff it into a global variable?

Clearly clueless here... any help would be appreciated.

--wpd

**Comment by bradfier** [comment]
My first concern would be that in a 'modern' environment (i.e. a docker container, something like Heroku, maybe even Kubernetes) the web application often does not know the external IP that traffic is reaching it on.

If you definitely need this, a neater way than throwing everything in a global static might be to create an empty `Arc<OnceCell<SocketAddr>>>`, pass a clone of that `Arc` into the handler as you construct it, then populate the `OnceCell` from the `socket_addr()` call when you are able to make it.

**Comment by wpd** [comment]
I am implementing a web server for an embedded device.  So I don't need to worry about docker containers and such.

I am an embedded development expert, not a web development expert, so I don't really know what I'm doing here.  But I need to figure out what to stuff in the line from the `examples/websocket.rs` example that currently reads:
```
                    var socket = new WebSocket(\"ws://localhost:8000/ws\", \"echo\");
```
`localhost` is clearly the wrong address.  I need to use the address of the server hosting the web server... which may be a dynamic IP address provided by a DHCP server to my embedded device.

Unfortunately... after spending the morning fighting with the borrow checker, and eventually going with the global variable route  (similar to what you describe above), I learned that the `server_addr()` method of `rouille` returns the same `0.0.0.0` server address with which I started the server.
So, I'm back to square 1...
How can I determine the address of the server on which the incoming request was received so as to pass that address on to a websocket call?

All clues and help will be gratefully appreciated! :-)

**Comment by wpd** [comment]
Apparently, I could have just used something like:
```
  var socket = new WebSocket("ws://" + location.host + "/firmware-update-ws", "status");
```
in my javascript code.  I think I'll take that for a spin and see if it gets me where I want to go.
