### ISSUE TITLE
What or, is best used with Rouille?

### ISSUE THREAD

**Issue by jhjacobs81** [tomaka/rouille#256]
I am at a point where i can use rouille for a basic web app, but whatever i try i can not get mysql to work. I keep getting errors after error, even though it works in other examples.

so what would be the best way to make rouille work with a database? Obviously the example isn’t good for me as it only handles one connection at a time.

**Comment by bradfier** [comment]
Hey @jhjacobs81, could you post an example of what you're trying and which isn't working for you?

The most basic setup that should work with Rouille would be to use [MySQL](https://docs.rs/mysql/latest/mysql/).

This slightly contrived example should get you started:
```rust
use std::net::{IpAddr, SocketAddr};
use mysql::*;
use mysql::prelude::*;
use rouille::router;

fn main() {
    let socket = SocketAddr::new(IpAddr::from([127, 0, 0, 1]), 3306);
    let opts = OptsBuilder::new().db_name(Some("my_db")).bind_address(Some(socket));
    let pool = Pool::new(opts).unwrap();
    rouille::start_server("127.0.0.1:5000", move |request| {
        router!(request,
           (GET) (/) => {
                let mut conn = pool.clone().get_conn().unwrap();
                let value: Option<i64> = conn.query_first("SELECT COUNT(*) FROM my_table").unwrap();
                rouille::Response::text(format!("Total: {}", value.unwrap_or(0)))
            },
            _ => rouille::Response::empty_404()
        )
    });
}
```

**Comment by jhjacobs81** [comment]
Hello @bradfier thanks for responding!

I had something along the lines of this:

`use mysql::*;
use mysql::prelude::*;
use rouille::router;

pub struct Pagedata {
    pub id: u64,
    pub title: String,
    pub body: String
}


fn main() {
    let mysqladdress = "mysql://user:password@127.0.0.1:3306/database";
    let opts = Opts::from_url(mysqladdress).unwrap();
    let pool = Pool::new(opts).unwrap();
    let mut conn = pool.get_conn().unwrap();

    rouille::start_server("127.0.0.1:8000", move |request| {
        router!(request,
           (GET) (/pageid) => {
                let p = conn
                .exec_map(
                "SELECT id, title, body FROM pages WHERE id = ?;",
                (&pageid,),
                |(id, title, body)| {
                Pagedata { id, title, body }
                },
                ).unwrap();

                rouille::Response::text(format!("ID: {} - Title: {} - Body: {}", p.id, p.title, p.body); 
            },
            _ => rouille::Response::empty_404()
        )
    });
}`

i tried moving around the mysql related let's to inside the routes etc etc.

What works for me now is this:
`use mysql::*;
use mysql::prelude::*;
use rouille::router;

fn main() {
    let mysqladdress = "mysql://user:password@127.0.0.1:3306/database";
    let opts = Opts::from_url(mysqladdress).unwrap();
    let pool = Pool::new(opts).unwrap();

    rouille::start_server("127.0.0.1:8000", move |request| {
        router!(request,
           (GET) (/) => {
            let mut conn = pool.get_conn().unwrap();
                let value: Option<i64> = conn.query_first("SELECT COUNT(*) FROM pages").unwrap();
                rouille::Response::text(format!("Total: {}", value.unwrap_or(0)))
            },
            _ => rouille::Response::empty_404()
        )
    });
}`

**Comment by jhjacobs81** [comment]
i cant even get that stupid github code formatting to work :/

**Comment by jhjacobs81** [comment]
> Hey @jhjacobs81, could you post an example of what you're trying and which isn't working for you?
> 
> The most basic setup that should work with Rouille would be to use [MySQL](https://docs.rs/mysql/latest/mysql/).
> 
> This slightly contrived example should get you started:
> 
> ```rust
> use std::net::{IpAddr, SocketAddr};
> use mysql::*;
> use mysql::prelude::*;
> use rouille::router;
> 
> fn main() {
>     let socket = SocketAddr::new(IpAddr::from([127, 0, 0, 1]), 3306);
>     let opts = OptsBuilder::new().db_name(Some("my_db")).bind_address(Some(socket));
>     let pool = Pool::new(opts).unwrap();
>     rouille::start_server("127.0.0.1:5000", move |request| {
>         router!(request,
>            (GET) (/) => {
>                 let mut conn = pool.clone().get_conn().unwrap();
>                 let value: Option<i64> = conn.query_first("SELECT COUNT(*) FROM my_table").unwrap();
>                 rouille::Response::text(format!("Total: {}", value.unwrap_or(0)))
>             },
>             _ => rouille::Response::empty_404()
>         )
>     });
> }
> ```



> Hey @jhjacobs81, could you post an example of what you're trying and which isn't working for you?
> 
> The most basic setup that should work with Rouille would be to use [MySQL](https://docs.rs/mysql/latest/mysql/).
> 
> This slightly contrived example should get you started:
> 
> ```rust
> use std::net::{IpAddr, SocketAddr};
> use mysql::*;
> use mysql::prelude::*;
> use rouille::router;
> 
> fn main() {
>     let socket = SocketAddr::new(IpAddr::from([127, 0, 0, 1]), 3306);
>     let opts = OptsBuilder::new().db_name(Some("my_db")).bind_address(Some(socket));
>     let pool = Pool::new(opts).unwrap();
>     rouille::start_server("127.0.0.1:5000", move |request| {
>         router!(request,
>            (GET) (/) => {
>                 let mut conn = pool.clone().get_conn().unwrap();
>                 let value: Option<i64> = conn.query_first("SELECT COUNT(*) FROM my_table").unwrap();
>                 rouille::Response::text(format!("Total: {}", value.unwrap_or(0)))
>             },
>             _ => rouille::Response::empty_404()
>         )
>     });
> }
> ```

**Comment by bradfier** [comment]
Well, at least with regard to your latest error, that's because `page` is actually a `Vec<Pagedata>`, I.e. it could contain none, one, or many `Pagedata`. You need to act on them individually (perhaps by accessing `page[0].title`) or collectively, perhaps using `map()` like below:

Try instead:

```rust
let response_text = page.into_iter().map(|p| format!("{} - {} - {}", p.id, p.title, p.body)).join("\n");
rouille::Response::text(response_text)
```

**Comment by jhjacobs81** [comment]
Thank you foryour response :)

unfortunatly, that throws out a whole new error :) As a resut, i believe i am not ready yet to work with Rouille so i have dropped it for now :(

Will keep an eye on it though ;-)

**Comment by bradfier** [comment]
Please do come back when you're interested again 🙂

**Comment by jhjacobs81** [comment]
which would be now :)

interest was never a problem, i very much like Rouille. i gotten further with it then with other frameworks, just not the mysql part. This is all on me, im a noob programmer stil :)

**Comment by jhjacobs81** [comment]
i thought an ORM would be better, but that throws errors too :(

Perhaps someone could create an example with an ORM
