### ISSUE TITLE
use `sha1-smol` instead of `sha1` to reduce dependencies?

### ISSUE THREAD

**Issue by hismito** [tomaka/rouille#267]
`sha1` was renamed to `sha1-smol` in [this commit](https://github.com/mitsuhiko/sha1-smol/commit/f7e44ee3a0f5bf0a7d7eea6227222ca4bb0c0c14)

**Comment by bradfier** [comment]
I'll need to take a look and see what if any requirements there are for changing over - thanks for the note!
