### ISSUE TITLE
Use a custom derive for POST input structs

### ISSUE THREAD

**Issue by tomaka** [tomaka/rouille#50]
This is a follow-up to #49 

Once it's stable (https://github.com/rust-lang/rust/issues/35900), we can use the custom derive system for POST structs instead of using `rustc-serialize`.

This has the big advantage that we can adjust the corresponding trait to our needs, and make it work for files.

```rust
trait DecodePostField {
    fn from_field(content: &str) -> Result<Self, PostError>;
    fn from_file<R: BufRead>(file: R, mime: &str) -> Result<Self, PostError>;
}

trait DecodePostInput {
    fn decode<I: Iterator<Item = PostInputElement>>(elements: I) -> Result<Self, PostError>;
}
```

Example in practice:

```rust
#[derive(RouillePostDecode)]      // implements DecodePostInput on the struct
struct Input {
    field1: i32,         // each field must implement DecodePostField
    field2: String,
    file: TemporaryFileStorage,
}

let input: Input = try_or_400!(rouille::post::decode(&request));
```

If you read #49 I explain at the bottom that it isn't possible to do this. But if we use a trait other than the one in rustc-serialize, then it becomes a viable option.

In this example, the `from_file` method of `TemporaryFileStorage` would write the file to a temporary directory by streaming from the user's request, and then will return a `TemporaryFileStorage` struct that contains the path to the file. If the `TemporaryFileStorage` struct gets dropped before being stored in a database (for example because of a panic), its destructor would automatically delete the file.

Rouille could provide some helpers, like:
- `TemporaryFileStorage`
- `BufferedFile` (stores the content in memory)

There is one unresolved question, however: how do we provide a configuration for `TemporaryFileStorage` or `BufferedFile`? While these two cases don't need a configuration, it would be nice if we could write a `S3File` struct that automatically uploads to S3 or a `ProxyFile` that transfers the file to another service. But doing so requires some sort of configuration to be passed to `from_file`.

**Comment by keeperofdakeys** [comment]
The macros 1.1 api supports white-listing attributes to provide configuration. If you use `#[derive(Foo, attributes(Bar)]`, any attributes like `#[Bar(config = "asdf")]` will be ignored by the compiler. In your derive function, you can then detect these attributes in the item, and provide a different implementation based on them.

**Comment by tomaka** [comment]
@keeperofdakeys That's a good thing to keep in mind, but in practice I don't think it helps.
You probably want to pass some sort of socket, or at least some values known only at runtime, both of which are not possible with this.

**Comment by keeperofdakeys** [comment]
Then have a function on the trait that takes the runtime configuration as input. If you need some kind of persistent state to perform multiple operations, you could also return a handle (like how an Iterator is a separate type to the collection).

So I don't see how macros 1.1 would help or hinder you here.

**Comment by tomaka** [comment]
> Then have a function on the trait that takes the runtime configuration as input.

Well, it's not as easy to do that. I'd like to avoid possible panics as much as possible, and I don't want for example to panic if the user forgets to pass the configuration. Instead it should be caught at compile-time.

**Comment by keeperofdakeys** [comment]
If the function includes the configuration as a parameter, the compiler can enforce this for you. In the case of something like a File object, you obviously need to have previously created a valid one to pass it in. If there is some kind of runtime error that could occur, the function should return a Result. Then the programmer has the choice of whether the error should be handled in some way (giving the user an error message), or whether the program should just panic.

Sorry if I'm not being very helpful here, I haven't looked into your use case.

**Comment by tomaka** [comment]
After thinking about it, I think the best solution is to use a macro instead, like this:

```rust
let input = decode_post!(&request, {
    field1: i32,
    field2: String,
    file: TemporaryFileStorage { path: "/tmp" },
})?;

let something = input.field1 * 2;
...
```

**Comment by tomaka** [comment]
I'm currently working on this.

After some tests, I'm changing to this syntax:

```rust
let input = decode_post!(&request, {
    field1: i32,
    field2: String,
    file: TemporaryFileStorage with TemporaryFileStorageConfig { path: "/tmp" },
})?;
```

And:

```rust
trait DecodePostField<Config> {
    fn from_field(config: Config, content: &str) -> Result<Self, PostError>;
    fn from_file<R: BufRead>(Self::Config, file: R, filename: Option<&str>, mime: &str) -> Result<Self, PostError>;
}
```

This way the user can pass different option types. For example `TemporaryFileStorage` can implement both `DecodePostField<()>` and `DecodePostField<TemporaryFileStorageConfig>`, which means that the user can either pass no configuration to `TemporaryFileStorageConfig`.
