### ISSUE TITLE
Use of gh-pages for book hosting

### ISSUE THREAD

**Issue by Phrohdoh** [tomaka/rouille#66]
I really like the usage of `gh-pages` for hosting the book.

Would you write up (blog post, etc) a how-to for this so that other projects may follow along?

I'd be great to see more do this, but unfortunately most of the gh-pages generation I have seen (my own included) just push the orphaned results of `cargo doc` and call that a day.

**Comment by tomaka** [comment]
Well, it's just this code: https://github.com/tomaka/rouille/blob/55d8d271d69fadc785010874a95374ee25947f7b/.travis.yml#L13-L24

**Comment by Phrohdoh** [comment]
I see, that is pretty clever and simple.
Thanks!

I'm closing this as there isn't any more to be done here.
