### ISSUE TITLE
Support SSL

### ISSUE THREAD

**Issue by tomaka** [tomaka/rouille#90]
Both for the listening server and the reverse proxy thing.

**Comment by PureW** [comment]
Could this be an optional feature so that those of us who would run rouille behind something like nginx can avoid ssl-dependencies?

**Comment by coder543** [comment]
It looks like tiny_http [supports SSL](https://github.com/tiny-http/tiny-http/blob/master/examples/ssl.rs), so what are the particular challenges here?

**Comment by coder543** [comment]
I can use an `nginx` proxy, so it's not a blocker for me, but it is nice to have everything in a single binary sometimes.

**Comment by CamJN** [comment]
This seems to just hang: https://gist.github.com/CamJN/4369785b198a6dd513f75c8ad24023bd

**Comment by CamJN** [comment]
@glennw What platform(s) did you test on? I can't get a super simple test project to actually serve a response on macOS, it hangs for me after making the tls connection and receiving the request. (see above gist for my non-working example).

**Comment by glennw** [comment]
@CamJN I only tested on Ubuntu 17.10 and 18.04.
